energy-savings-scheme/rules-interface

src/pages/base_eligibility/BaseEligibility.jsx, src/pages/base_eligibility/LoadClausesBaseEligibility.jsx, src/pages/commercial_ac/CertificatEstimatorLoadClauses.jsx, src/pages/commercial_ac/LoadClauses.jsx, src/pages/commercial_motors/CertificateEstimatorLoadClausesMotors.jsx, src/pages/commercial_motors/LoadClausesSYS1.jsx, src/pages/commercial_wh/CertificateEstimatorLoadClausesWH.jsx, src/pages/commercial_wh/LoadClausesWh.jsx, src/pages/homepage/Homepage.jsx, src/pages/pool_pumps/CertificateEstimatorLoadClausesPP.jsx, src/pages/pool_pumps/LoadClausesActivityReqSYS2.jsx, src/pages/refrigerated_cabinets/CertificatEstimatorLoadClausesRC.jsx, src/pages/refrigerated_cabinets/LoadClauses.jsx, src/pages/residential_ac/CertificateEstimatorResidentialACLoadClauses.jsx, src/pages/residential_ac/LoadClausesActivityRequirements.jsx, src/pages/residential_refrigerators/CertificateEstimatorLoadClausesRefrigerators.jsx, src/pages/residential_refrigerators/LoadClauses.jsx
copy changes as per David's feedback
=> Merge to master from nonprod 

src/pages/base_eligibility/BaseEligibility.jsx, src/pages/commercial_ac/CertificatEstimatorLoadClauses.jsx, src/pages/commercial_motors/CertificateEstimatorLoadClausesMotors.jsx, src/pages/commercial_wh/CertificateEstimatorLoadClausesWH.jsx, src/pages/pool_pumps/CertificateEstimatorLoadClausesPP.jsx, src/pages/refrigerated_cabinets/CertificatEstimatorLoadClausesRC.jsx, src/pages/residential_ac/CertificateEstimatorResidentialACLoadClauses.jsx, src/pages/residential_refrigerators/CertificateEstimatorLoadClausesRefrigerators.jsx
- Change UI flow
- Change Wh climate zone
=> Merge to master 

src/pages/BESS1/CertificateEstimatorBESS1.jsx
* Create dummy content changes in BESS1 to test the `nonprod` deployment
* Added `&nbsp;` to the end of the description content
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-1693
- Content changes highlighted:
None
=> [DG22-1693] Create test deployment for nonprod

docs/bruno/openfisca/estimate-certificates/BESS1_V5Nov24/BESS1_V5Nov24_PRC_calculation.bru, package-lock.json, src/components/calculate/CalculateBlock.js, src/components/calculate/CalculateForm.js, src/pages/BESS1/ActivityRequirementsBESS1.jsx, src/pages/BESS1/CertificateEstimatorBESS1.jsx, src/pages/BESS1/CertificateEstimatorLoadClausesBESS1.jsx, src/pages/commercial_wh/LoadClausesWh.jsx, src/types/openfisca_variables.js, src/types/value_type.js
* Update UI for BESS1 Eligibility updates
* Change variables from BESS1_PDRSAug24 to BESS1_V5Nov24
* Remove unused console.log()
* Remove hardcoded value into constants and types
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-1691
None
=> [DG22-1691] Update BESS1 eligibility

src/components/calculate/CalculateForm.js, src/pages/BESS2/ActivityRequirementsBESS2.jsx, src/pages/BESS2/CertificateEstimatorBESS2.jsx, src/pages/BESS2/CertificateEstimatorLoadClausesBESS2.jsx, src/types/openfisca_variables.js
* Update UI for BESS2 Eligibility updates
* Change variables from BESS2_PDRSAug24 to BESS2_V5Nov24
* Remove unused console.log()
* Add openfisca variables to `types/openfisca_variables.js`
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-1692
None
[DG22-1692]: https://essnsw.atlassian.net/browse/DG22-1692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DG22-1692] Update BESS2 eligibility UI

scripts/dist-build.ts, src/components/certificate/BESSBrandSelector.js, src/pages/BESS1/CertificateEstimatorBESS1.jsx, src/pages/BESS1/CertificateEstimatorLoadClausesBESS1.jsx, src/services/registry_api.js, src/types/openfisca_variables.js
* Update BESS1 certifcate UI for new registry values 
* Add new component for for selecting brand & models
* Auto fill usable battery capacity
* Remove unused console.log() & import
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-1689
[DG22-1689]: https://essnsw.atlassian.net/browse/DG22-1689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DG22-1689] BESS1 Certificates: UI hookup for new registry values

src/pages/BESS1/ActivityRequirementsBESS1.jsx, src/pages/BESS2/ActivityRequirementsBESS2.jsx, src/pages/homepage/SolarBatteryEligibility.jsx
* Update copy of BESS1 & BESS2 eligibility pages
* Update copy text BESS1 & BESS2 eligibility pages
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-1718
- None
[DG22-1718]: https://essnsw.atlassian.net/browse/DG22-1718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DG22-1718] Update BESS copy

.github/workflows/build-deploy-dev.yml, .github/workflows/build-deploy-prod.yml, .github/workflows/build-deploy-staging.yml
* Production ready release
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-1752
Standalone page: https://essestimatorui.z8.web.core.windows.net/#/commercial-ac-estimator
JS: https://essestimatorui.z8.web.core.windows.net/dist/latest/files/commercial_ac_estimator.js
[DG22-1752]: https://essnsw.atlassian.net/browse/DG22-1752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DG22-1752] Deploy the new v5 code packets for HVAC2 fixes

src/pages/commercial_wh/ActivityRequirementsWaterHeater.jsx, src/pages/commercial_wh/CertificateEstimatorLoadClausesWH.jsx, src/pages/commercial_wh/CertificateEstimatorWH.jsx
* fixing duplicate header and footer in f16 eligibility page
* fixing duplicate header and footer in f16 certificate estimator page
* remove unused code in certificate and eligibility page
* update workflow dev, staging and prod
* add conditional render for header and footer in fe16 eligibility page
* add conditional render for header and footer in fe16 certificate page
* add new env variable `IS_DRUPAL_PAGES` to all existing workflow
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-1843
- None 
- None
- None
[DG22-1843]: https://essnsw.atlassian.net/browse/DG22-1843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0 …
=> [DG22-1843] Test Updates on Drupal Staging

src/pages/commercial_wh/CertificateEstimatorWH.jsx
* Removing double up header text for Drupal environment
None
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-1843
- None
- None
- None
[DG22-1843]: https://essnsw.atlassian.net/browse/DG22-1843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DG22-1843] Fix double up header text

src/components/calculate/CalculateForm.js, src/pages/commercial_wh/CertificateEstimatorWH.jsx, src/types/openfisca_variables.js
* Remove PRC copy on f16 certificate section heading
* Remove PRC text
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-1966
- None 
- None
- None
[DG22-1966]: https://essnsw.atlassian.net/browse/DG22-1966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DG22-1966] Fix copy

src/components/calculate/CalculateForm.js, src/pages/commercial_wh_F16_gas/CertificateEstimatorF16_gas.jsx, src/pages/commercial_wh_F16_gas/CertificateEstimatorLoadClausesF16_gas.jsx, src/types/openfisca_variables.js
* Apply conditional render header and footer based on IS_DRUPAL_PAGES variable
* Apply conditional render header and footer based on IS_DRUPAL_PAGES variable
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-1966
- None 
- 
[DG22-1966]: https://essnsw.atlassian.net/browse/DG22-1966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DG22-1966] Apply conditional render header and footer based on IS_DRUPAL_PAGES variable

src/components/calculate/CalculateForm.js, src/pages/commercial_wh_F16_gas/CertificateEstimatorF16_gas.jsx, src/pages/commercial_wh_F16_gas/CertificateEstimatorLoadClausesF16_gas.jsx, src/types/openfisca_variables.js
* DG22-1968
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-1968
- None
- None
=> Release 20250225

src/components/calculate/CalculateForm.js, src/pages/commercial_wh/CertificateEstimatorLoadClausesWH.jsx, src/pages/commercial_wh/CertificateEstimatorWH.jsx, src/pages/commercial_wh_F16_gas/ActivityRequirementsWaterHeater.jsx, src/pages/commercial_wh_F16_gas/CertificateEstimatorF16_gas.jsx, src/pages/commercial_wh_F16_gas/LoadClausesF16_gas.jsx, src/types/openfisca_variables.js
* Change f16 electric variable for certificate page
* Change variable from _WH1_F16_electric_PDRSAug24_ to _F16_electric_PDRSDec24_
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-1976
- None 
-  None 
-  None 
[DG22-1976]: https://essnsw.atlassian.net/browse/DG22-1976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DG22-1976] F16 electric certificates new correct variable set

src/components/calculate/CalculateBlock.js, src/lib/analytics.js, src/pages/pool_pumps/ActivityRequirementsSYS2.jsx, src/pages/pool_pumps/CertificateEstimatorLoadClausesPP.jsx, src/pages/pool_pumps/CertificateEstimatorPP.jsx
* Fix feedback form ui position
* Performance improvement
* bugfix - reset selected model whenever brand changed
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-1942
- None 
- 
- 
[DG22-1942]: https://essnsw.atlassian.net/browse/DG22-1942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DG22-1942] add new segment capture, feedback button and GA integration in pool pump certificate page

src/App.js, src/components/calculate/CalculateForm.js, src/components/feedback/feedback.js, src/constant/user-type.js, src/index.js, src/lib/analytics.js, src/pages/pool_pumps/ActivityRequirementsSYS2.jsx, src/pages/pool_pumps/CertificateEstimatorLoadClausesPP.jsx, src/pages/pool_pumps/CertificateEstimatorPP.jsx, src/pages/pool_pumps/LoadClausesActivityReqSYS2.jsx
* Remove api list variables and list activities from root apps.
* Add conditional render on Drupal pages env variables
* Exclude path url residential pool pump certificate from executes list variables and activities api
* Apply performance improvement for pool pump activity (certificate & eligibility)
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-1942
- None 
- None
[DG22-1942]: https://essnsw.atlassian.net/browse/DG22-1942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DG22-1942] Fixing performance improvement for pool pumps pages

src/components/calculate/CalculateForm.js, src/pages/commercial_wh_f17/CertificateEstimatorF17.jsx, src/pages/electric_residential_heat_pumps/CertificateEstimatorD17.jsx, src/pages/gas_residential_heat_pumps/CertificateEstimatorD19.jsx, src/pages/residential_solar_water_heater_D18/CertificateEstimatorD18.jsx, src/pages/residential_solar_water_heater_gas_replacement_D20/CertificateEstimatorD20.jsx, src/types/openfisca_variables.js
* remove prc copy in D17, D18, D19, D20, and F17 certificate pages
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-2201
- None 
- 
-
=> DG22-2201 - v6 Batch 2, Remove PRC Copy

src/components/certificate-price/CertificiatePrice.js, src/pages/residential_ac/CertificateEstimatorResidentialAC.jsx, src/pages/residential_ac/CertificateEstimatorResidentialACLoadClauses.jsx, src/services/registry_api.js
* add new component certificate price
* implement certificate price to residential ac certificate page
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-2301
- None 
- 
- 
[DG22-2301]: https://essnsw.atlassian.net/browse/DG22-2301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DG22-2301] Add certificate price to residential ac certificate page

src/pages/BESS1/CertificateEstimatorBESS1.jsx, src/pages/BESS2/CertificateEstimatorBESS2.jsx, src/pages/commercial_ac/CertificateEstimator.jsx, src/pages/commercial_motors/CertificateEstimatorMotors.jsx, src/pages/commercial_wh/CertificateEstimatorWH.jsx, src/pages/commercial_wh_F16_gas/CertificateEstimatorF16_gas.jsx, src/pages/commercial_wh_f17/CertificateEstimatorF17.jsx, src/pages/electric_residential_heat_pumps/CertificateEstimatorD17.jsx, src/pages/gas_residential_heat_pumps/CertificateEstimatorD19.jsx, src/pages/pool_pumps/CertificateEstimatorPP.jsx, src/pages/refrigerated_cabinets/CertificatEstimatorLoadClausesRC.jsx, src/pages/refrigerated_cabinets/CertificateEstimatorRC.jsx, src/pages/residential_ac/CertificateEstimatorResidentialAC.jsx, src/pages/residential_refrigerators/CertificateEstimatorRefrigerators.jsx, src/pages/residential_solar_water_heater_D18/CertificateEstimatorD18.jsx, src/pages/residential_solar_water_heater_gas_replacement_D20/CertificateEstimatorD20.jsx
* adjust white space in all certificate pages
* add product class information in all step at refrigerated cabinets certificate page
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-2333
- None 
- None
- None
[DG22-2333]: https://essnsw.atlassian.net/browse/DG22-2333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> # [DG22-2333] Streamline whitespace gap in all certificates pages 

src/components/calculate/CalculateBlock.js, src/pages/commercial_wh/ActivityRequirementsWaterHeater.jsx, src/types/openfisca_variables.js
[DG22-2467]  Add new question split system and safety requirement
* Add 2 new questions split system and safety requirement
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-2467
- None 
- None
- None
[DG22-2467]: https://essnsw.atlassian.net/browse/DG22-2467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DG22-2467] F16 Electric eligibility: update with ESS 2025 requirements

src/components/calculate/CalculateBlock.js, src/pages/commercial_wh_f17/ActivityRequirementsWaterHeater.jsx, src/types/openfisca_variables.js
[DG22-2498] New Question from ESS Rule Change 2025
* Add 2 new questions split system and safety requirement.
* Adjust storage volume question from select dropdown to radio button.
* Remove logic to set select dropdown value.
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-2498
- None 
- None
- None
[DG22-2498]: https://essnsw.atlassian.net/browse/DG22-2498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DG22-2498] - F17 eligibility: Frontend and UI ESS Rule Change 2025

src/components/calculate/CalculateBlock.js, src/pages/gas_residential_heat_pumps/ActivityRequirementsD19.jsx, src/types/openfisca_variables.js
[DG22-2497] New Question from ESS Rule Change 2025
* Add 2 new questions split system and safety requirement.
* Remove unrelevant code.
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-2497
- None 
- None
- None
[DG22-2497]: https://essnsw.atlassian.net/browse/DG22-2497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DG22-2497] - D19 eligibility: Frontend and UI ESS Rule Change 2025

src/pages/BESS2/CertificateEstimatorLoadClausesBESS2.jsx
* hide certificate price 
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-2461
- None 
- None
- None
=> [DG22-2461] BESS2 certificates: update functionality to prevent misinterpretation and misuse

.github/workflows/build-deploy-dev.yml
* change secret variable name for dev workflow
**Links**
- Jira Ticket : https://essnsw.atlassian.net/browse/DG22-2537
- None 
- None
- None
=> [DG22-2537] - Infra: Decommission stage 2

.github/workflows/build-deploy-dev.yml, .github/workflows/build-deploy-prod.yml, .github/workflows/build-deploy-staging.yml, src/dynamic-loader.js, src/pages/commercial_motors/CertificateEstimatorLoadClausesMotors.jsx
* add step to copy dynamic loader script in github action pipeline
* add period for cache testing in commercial motors
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-2517
- None 
- None
- None
=> [DG22-2517] - Revisit caching strategy for rules interface files
